#!/bin/bash

#SBATCH --job-name=vb-master
#SBATCH --output=/vol/miltank/users/bilv/ldm/slurm/%x-%A.out
#SBATCH --error=/vol/miltank/users/bilv/ldm/slurm/%x-%A.err
#SBATCH --mail-user=valentin.biller@tum.de
#SBATCH --mail-type=ALL
#SBATCH --partition=universe,asteroids
#SBATCH --qos=master
#SBATCH --time=3-00:00:00
#SBATCH --gres=gpu:0,gpumem:0G
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G

cd /vol/miltank/users/bilv/ldm
uv run /vol/miltank/users/bilv/ldm/inference_diffusion.py \
    --function calculate_metrics \
    --model big \
    --scheduler ddpm \
    --version 2 \
    --mode inpainting_inference_conditioning \
    --denoising repaint
### 'inference'
### 'inference_challenge'
### 'inference_conditioning'