#!/bin/bash

#SBATCH --job-name=vb-master
#SBATCH --output=/vol/miltank/users/bilv/ldm/slurm/%x-%A.out  ###/vol/miltank/users/bilv/master-thesis/models/ldm-diffusion/slurm/%x-%A.out
#SBATCH --error=/vol/miltank/users/bilv/ldm/slurm/%x-%A.err  ###/vol/miltank/users/bilv/master-thesis/models/ldm-diffusion/slurm/%x-%A.err
#SBATCH --mail-user=valentin.biller@tum.de
#SBATCH --mail-type=ALL
#SBATCH --partition=universe
#SBATCH --qos=master
#SBATCH --time=7-00:00:00
#SBATCH --gres=gpu:1,gpumem:40G
#SBATCH --cpus-per-task=16
#SBATCH --mem=128G

cd /vol/miltank/users/bilv/ldm
uv run /vol/miltank/users/bilv/ldm/train_diffusion.py --mlflow_info_slot 1 --controlnet --save_samples_every 5

### unet:  ddpm - mask:  no / modality:  no - uv run /vol/miltank/users/bilv/ldm/train_diffusion.py --mlflow_info_slot 0 --model unet --scheduler ddpm --mask_conditioning none --modality-conditioning
### unet:  ddpm - mask:  no / modality: yes - uv run /vol/miltank/users/bilv/ldm/train_diffusion.py --mlflow_info_slot 1 --model unet --scheduler ddpm --mask_conditioning none --save_samples_every 5
### unet:  ddpm - mask: 256 / modality: yes - uv run /vol/miltank/users/bilv/ldm/train_diffusion.py --mlflow_info_slot 2 --model unet --scheduler ddpm --mask_conditioning 256 --save_samples_every 5

### unet: iddpm - mask:  64 / modality: yes - uv run /vol/miltank/users/bilv/ldm/train_diffusion.py --mlflow_info_slot 3 --model unet --scheduler iddpm --mask_conditioning 64 --save_samples_every 5 --mlflow_use  # TODO --mlflow_use
###  dit: iddpm - mask:  64 / modality: yes - uv run /vol/miltank/users/bilv/ldm/train_diffusion.py --mlflow_info_slot 4 --model dit --scheduler iddpm --mask_conditioning 64 --save_samples_every 5 --mlflow_use  # TODO --mlflow_use

