#!/bin/bash

#SBATCH --job-name=vb-master
#SBATCH --output=/vol/miltank/users/bilv/master-thesis/models/ldm-diffusion/slurm/%x-%A.out
#SBATCH --error=/vol/miltank/users/bilv/master-thesis/models/ldm-diffusion/slurm/%x-%A.err
#SBATCH --mail-user=valentin.biller@tum.de
#SBATCH --mail-type=ALL
#SBATCH --partition=universe,asteroids
#SBATCH --qos=master
#SBATCH --time=3-00:00:00
#SBATCH --gres=gpu:4,gpumem:80G
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G

cd /vol/miltank/users/bilv/ldm
uv run /vol/miltank/users/bilv/ldm/train_diffusion.py